# Generated by Django 4.2.6 on 2023-12-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bank_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='current',
            field=models.FloatField(default=0.0),
        ),
    ]
