// import Head from 'next/head'
/* 
<Head>
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="icon" href="/favicon.ico" />
</Head> 
*/
// import Image from 'next/image'
//see if I have to instal sharp to use images on producton
/* 
<Image
  src="/vercel.svg"
  alt="Vercel Logo"
  className={styles.vercelLogo}
  width={100}
  height={24}
  priority
/> 
*/

// Global styles
// import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';

import Container from 'react-bootstrap/Container';
import {SpotManager} from '../features/spot/SpotManager'
import {BankManager} from '../features/bank/BankManager'
import { MyContextProvider } from '../context/context';
import BinanceTicker from './api/BinanceTicker';

export default function Home() {
  return (
    <MyContextProvider>
      <BinanceTicker />
      <Container>
        <SpotManager />
        <BankManager />
      </Container>
    </MyContextProvider>

  )
}
